name: CI of the project

on:
  pull_request:
    branches:
     - master

jobs:
  build:
    name: Build nodejs app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
      
      - name: install dependencies
        run: npm install
      
      
